Update Jenkinsfile
universidad-de-cartagena/ejemplo-python pull request #3
Opened 2019-08-17 20:56 UTC by JenkinsUDC

2019-08-17 20:58 UTC, AmauryOrtega requested changes

2019-08-17 20:58 UTC, AmauryOrtega commented on Jenkinsfile
> +        sh 'docker-compose down -v -t 0 --remove-orphans --rmi all || true'
Don't delete images using docker-compose here

2019-08-17 20:58 UTC, JenkinsUDC commented on Jenkinsfile
> +        sh 'docker-compose down -v -t 0 --remove-orphans --rmi all || true'
Okay, ya lo hago

2019-08-17 21:05 UTC, merged

2019-08-18 11:46 UTC, JenkinsUDC reviewed
We need to improve this. The database container is not being deleted for some reason. Maybe testing is needed?

2019-08-18 11:49 UTC, AmauryOrtega commented
@JenkinsUDC I agree. I created an issue for this.